version: "3.9"
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=todouser
    - POSTGRES_PASSWORD=todopassword

  api_python:
    build: python/.
    ports:
    - "5000"
    environment:
    - POSTGRES_USER=todouser
    - POSTGRES_PASSWORD=todopassword
    - POSTGRES_HOST=db
    depends_on:
    - db
