version: "3.9"
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=todouser
    - POSTGRES_PASSWORD=todopassword

  api_rust:
    build: api-rust/.
    environment:
    - POSTGRES_USER=todouser
    - POSTGRES_PASSWORD=todopassword
    - POSTGRES_HOST=db
    depends_on:
    - db


  api_python:
    build: api-python/.
    environment:
    - POSTGRES_USER=todouser
    - POSTGRES_PASSWORD=todopassword
    - POSTGRES_HOST=db
    depends_on:
    - db
    
  api_nodejs:
    build: api-nodejs/.
    environment:
    - PGUSER=todouser
    - PGPASSWORD=todopassword
    - PGHOST=db
    - PGPORT=5432
    depends_on:
    - db    

  react:
    build: todo-react/.
    ports:
    - "3000:3000"
    depends_on:
    - api_python
  proxy:
    build: proxy/.
    ports:
    - "8000:80"
    depends_on:
    - api_python
    - react
